### ISSUE TITLE
Disable back functionality

### ISSUE THREAD

**Issue by christianvictoria** [gr4vy/gr4vy-android#3]
While processing payment, user can still press back button/gesture of the device therefore it will trigger Cancelled event but the payment is already successful. 

Is there a way to disable back button/gesture before launching the Gr4vySDK? I've tried onBackPressed, onKeyDown but the device back functionality is still enabled after launching the Gr4vySDK.

**Comment by cbetta** [comment]
Hi @christianvictoria, thank you for reaching out. Can I ask what merchant you are working with?
